version: "3"

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.5.4"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - network.publish_host=127.0.0.1

networks:
  esnet:
    driver: bridge
