addSbtPlugin("io.get-coursier" %% "sbt-coursier" % "1.0.0-RC2")
addSbtPlugin("io.spray" %% "sbt-revolver" % "0.8.0")
addSbtPlugin("org.scala-js" %% "sbt-scalajs" % "0.6.16")
addSbtPlugin("com.vmunier" %% "sbt-web-scalajs" % "1.0.4")
addSbtPlugin("com.geirsson" %% "sbt-scalafmt" % "0.6.8")
