apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: orkestra
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
  - port: 9200
    targetPort: 9200

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-internal
  namespace: orkestra
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
  - port: 9300
    targetPort: 9300

---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: orkestra
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
        env:
        - name: cluster.name
          value: orkestra
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.zen.ping.unicast.hosts
          value: elasticsearch-internal
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: data
        emptyDir: {}
